name: Build

on:
  push:
    branches:    
      - main
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
      - name: Build Filesystem Image
        run: pio run --target buildfs --environment ulanzi
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            .pio/build/ulanzi/firmware.bin
            .pio/build/ulanzi/partitions.bin
            .pio/build/ulanzi/littlefs.bin
            ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin
          retention-days: 1        